#!/bin/bash

# Cloudflare Tunnel Setup Script
# Interactive script to configure Cloudflare Tunnel on Umbrel
# Usage: ./scripts/setup-cloudflare-tunnel.sh

set -e  # Exit on any error

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
UMBREL_HOST="umbrel@umbrel.local"
CLOUDFLARED_DIR="/home/umbrel/.cloudflared"
CONFIG_FILE="$CLOUDFLARED_DIR/config.yml"
DOMAIN="aggrandizedigital.com"
API_SUBDOMAIN="api.${DOMAIN}"

echo -e "${BLUE}================================================${NC}"
echo -e "${BLUE}  Cloudflare Tunnel Configuration Setup${NC}"
echo -e "${BLUE}================================================${NC}"
echo ""

# Check if cloudflared is installed
echo -e "${YELLOW}Checking cloudflared installation...${NC}"
if ! ssh "$UMBREL_HOST" "command -v cloudflared > /dev/null 2>&1"; then
    echo -e "${RED}Error: cloudflared is not installed on Umbrel!${NC}"
    echo ""
    echo "Please install cloudflared first:"
    echo "  ssh $UMBREL_HOST"
    echo "  wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
    echo "  sudo mv cloudflared-linux-arm64 /usr/local/bin/cloudflared"
    echo "  sudo chmod +x /usr/local/bin/cloudflared"
    exit 1
fi

CLOUDFLARED_VERSION=$(ssh "$UMBREL_HOST" "cloudflared --version 2>&1 | head -n 1")
echo -e "${GREEN}✓ cloudflared is installed: $CLOUDFLARED_VERSION${NC}"
echo ""

# Interactive tunnel ID input
echo -e "${YELLOW}Cloudflare Tunnel Setup${NC}"
echo "────────────────────────────────────────"
echo ""
echo "Before proceeding, you need to create a tunnel in Cloudflare Zero Trust:"
echo "  1. Go to https://one.dash.cloudflare.com/"
echo "  2. Navigate to Networks > Tunnels"
echo "  3. Click 'Create a tunnel'"
echo "  4. Choose 'Cloudflared' as connector type"
echo "  5. Give it a name (e.g., 'aggrandize-umbrel')"
echo "  6. Copy the Tunnel ID (format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)"
echo ""
read -p "Enter your Cloudflare Tunnel ID: " TUNNEL_ID

# Validate tunnel ID format (UUID)
if ! [[ $TUNNEL_ID =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
    echo -e "${RED}Error: Invalid tunnel ID format!${NC}"
    echo "Expected format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    exit 1
fi

echo ""
echo -e "${GREEN}✓ Valid tunnel ID received${NC}"
echo ""

# Prompt for tunnel credentials
echo -e "${YELLOW}Tunnel Credentials${NC}"
echo "────────────────────────────────────────"
echo ""
echo "Now you need the tunnel credentials JSON."
echo "In the Cloudflare dashboard, after creating the tunnel:"
echo "  1. Click 'Configure' on your tunnel"
echo "  2. You'll see a command like: cloudflared tunnel run <tunnel-id>"
echo "  3. Or download the credentials file directly"
echo ""
echo "Paste the entire JSON credentials (ends with }), then press Enter twice:"
echo ""

# Read multi-line JSON input
CREDENTIALS_JSON=""
while IFS= read -r line; do
    if [ -z "$line" ] && [ -n "$CREDENTIALS_JSON" ]; then
        break
    fi
    CREDENTIALS_JSON+="$line"$'\n'
done

# Validate JSON
if ! echo "$CREDENTIALS_JSON" | python3 -m json.tool > /dev/null 2>&1; then
    echo -e "${RED}Error: Invalid JSON format!${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Valid credentials JSON received${NC}"
echo ""

# Create cloudflared directory on Umbrel
echo -e "${YELLOW}Setting up configuration on Umbrel...${NC}"
ssh "$UMBREL_HOST" "mkdir -p $CLOUDFLARED_DIR"
echo -e "${GREEN}✓ Created directory: $CLOUDFLARED_DIR${NC}"

# Upload credentials file
echo "Uploading credentials file..."
echo "$CREDENTIALS_JSON" | ssh "$UMBREL_HOST" "cat > $CLOUDFLARED_DIR/${TUNNEL_ID}.json"
ssh "$UMBREL_HOST" "chmod 600 $CLOUDFLARED_DIR/${TUNNEL_ID}.json"
echo -e "${GREEN}✓ Credentials file uploaded: ${TUNNEL_ID}.json${NC}"

# Create config.yml with actual tunnel ID
echo "Creating tunnel configuration..."
ssh "$UMBREL_HOST" "cat > $CONFIG_FILE" << EOF
# Cloudflare Tunnel Configuration
# Auto-generated by setup-cloudflare-tunnel.sh

tunnel: $TUNNEL_ID
credentials-file: $CLOUDFLARED_DIR/${TUNNEL_ID}.json

ingress:
  # API endpoint
  - hostname: $API_SUBDOMAIN
    service: http://localhost:3333
    originRequest:
      noTLSVerify: false

  # Catch-all (required)
  - service: http_status:404
EOF

ssh "$UMBREL_HOST" "chmod 644 $CONFIG_FILE"
echo -e "${GREEN}✓ Configuration file created: config.yml${NC}"
echo ""

# Display configuration
echo -e "${BLUE}Generated Configuration:${NC}"
echo "────────────────────────────────────────"
ssh "$UMBREL_HOST" "cat $CONFIG_FILE"
echo "────────────────────────────────────────"
echo ""

# Test tunnel connection
echo -e "${YELLOW}Testing tunnel connectivity...${NC}"
echo "Running test connection (this may take a few seconds)..."

TEST_OUTPUT=$(ssh "$UMBREL_HOST" "timeout 10 cloudflared tunnel --config $CONFIG_FILE run 2>&1" || true)

if echo "$TEST_OUTPUT" | grep -q "Connection.*registered"; then
    echo -e "${GREEN}✓ Tunnel connection successful!${NC}"
elif echo "$TEST_OUTPUT" | grep -q "Registered tunnel connection"; then
    echo -e "${GREEN}✓ Tunnel connection successful!${NC}"
else
    echo -e "${YELLOW}⚠ Could not verify tunnel connection${NC}"
    echo "This might be normal. The tunnel will be started as a service."
    echo ""
    echo "Test output:"
    echo "$TEST_OUTPUT"
fi
echo ""

# Setup systemd service
echo -e "${YELLOW}Setting up systemd service...${NC}"
ssh "$UMBREL_HOST" << 'ENDSSH'
sudo tee /etc/systemd/system/cloudflared.service > /dev/null << 'EOF'
[Unit]
Description=Cloudflare Tunnel
After=network.target

[Service]
Type=simple
User=umbrel
ExecStart=/usr/local/bin/cloudflared tunnel --config /home/umbrel/.cloudflared/config.yml run
Restart=on-failure
RestartSec=10
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=cloudflared

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable cloudflared.service
sudo systemctl restart cloudflared.service
ENDSSH

echo -e "${GREEN}✓ Systemd service configured and started${NC}"
echo ""

# Wait for service to start
sleep 3

# Check service status
echo -e "${YELLOW}Checking service status...${NC}"
if ssh "$UMBREL_HOST" "sudo systemctl is-active --quiet cloudflared.service"; then
    echo -e "${GREEN}✓ cloudflared service is running!${NC}"
else
    echo -e "${YELLOW}⚠ Service may still be starting...${NC}"
fi
echo ""

# Display service status
ssh "$UMBREL_HOST" "sudo systemctl status cloudflared.service --no-pager -l | head -n 20"
echo ""

# DNS Configuration Instructions
echo -e "${BLUE}================================================${NC}"
echo -e "${GREEN}   Cloudflare Tunnel Setup Complete!${NC}"
echo -e "${BLUE}================================================${NC}"
echo ""
echo -e "${YELLOW}IMPORTANT: DNS Configuration Required${NC}"
echo "────────────────────────────────────────"
echo ""
echo "Your tunnel is now running, but you need to configure DNS:"
echo ""
echo "  1. Go to Cloudflare Zero Trust Dashboard:"
echo "     https://one.dash.cloudflare.com/"
echo ""
echo "  2. Navigate to your tunnel:"
echo "     Networks > Tunnels > [Your Tunnel]"
echo ""
echo "  3. Go to 'Public Hostname' tab"
echo ""
echo "  4. Add a public hostname:"
echo "     • Subdomain: api"
echo "     • Domain: $DOMAIN"
echo "     • Service: http://localhost:3333"
echo ""
echo "  OR configure in Cloudflare DNS:"
echo "     • Type: CNAME"
echo "     • Name: api"
echo "     • Target: ${TUNNEL_ID}.cfargotunnel.com"
echo "     • Proxy: Enabled (orange cloud)"
echo ""
echo -e "${YELLOW}Testing:${NC}"
echo "  After DNS propagation (1-5 minutes), test your API:"
echo -e "  ${BLUE}curl https://$API_SUBDOMAIN/health${NC}"
echo ""
echo -e "${YELLOW}Monitoring:${NC}"
echo "  View tunnel logs:"
echo -e "  ${BLUE}ssh $UMBREL_HOST 'sudo journalctl -u cloudflared -f'${NC}"
echo ""
echo -e "${YELLOW}Troubleshooting:${NC}"
echo "  If the tunnel doesn't connect, check:"
echo "    • Credentials file is correct"
echo "    • Tunnel ID matches in Cloudflare dashboard"
echo "    • Network connectivity from Umbrel"
echo "    • Service logs for errors"
echo ""
